language: python
python:
- '3.7'
services:
- redis
before_install:
- python$PY -m pip install Cython
- python$PY -m pip install numpy
- python$PY --version
- python$PY -m cython --version
- python$PY -c "import numpy;print(numpy.__version__)"
install:
- pip install .
script:
- pip install -r test-requirements.txt
- flake8 colmena/
- pytest colmena
deploy:
  provider: pypi
  user: __token__
  skip_existing: true
  distributions: sdist bdist_wheel
  password:
    secure: P/gfet/FfbSzpZJoiODLWvPUw/FeHU2VX2va+0hbwlX+MZhjuKN+GVUbjXvB84H+zCr0UonTWOh7Q+PlHb1TMlOlTF4Au2WK8k+g5neRTDDGnqKqzoxUiMdzL9pHJ8kLlWr+8DxtxaMy7YXEcmJdYtzBSf5OMdIXib1VbVV98p0KdQ83pykeI7XSdb4jiZYdgkAjWiA778p3xGmrvv3gtnkULnEpdTCVWMnb5JnufGbZndPC+OHi5juZs3AJ3OlwJttBL5yS58MYkWh3GBeGdaWG+9QZgqzk69Q5znbsirmLpMRS9sa5USccYYqKSpwr5afNllpIG7XGW/5zaWX9M6nxgEXkWwnDP4Gt+Gi+ILMlMhu0Gqxn2TA125Lm92IdzLLmkfcJCZaZIPlQ9OSxvyAdMsKV3BWA9jmjtZwmrbxMdytGXjrtuIKIMl+c0xLuojuQg1fQc0uk7XWXBiIuX7qGPccVO+UJcs8JCS0SuTqpRL8Ds1QwFw8CElVlemXMUgdhIi/cyVCXu8WJ3PtB8KutsUGa8ZEqMJ4Jg6swk52CjLRMmijQZyRCNfkg9HIiXJWTMxeV5atTdVGy3iP3EOrntvqrzDSKoWjQ2XB1vPe0v15ICiNOV6D+9hXCusGmyI/0PdXhj5GLPhy9vuLjTTDcdskgHIyD22/PZZpkYMM=
  on:
    tags: true
    branch: master
